# Generated by Django 2.2.12 on 2021-01-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    def create_data(apps, schema_editor):
        Ingredient = apps.get_model('foods', 'ingredient')
        Ingredient(name="test", store="a", price="1.24").save()

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
